batch_size: 32
# batch_size: 32  # default
#epochs: 1000
epochs: 300
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 1
weight_decay: 1e-4
fp16_precision: True
pixpro_pos_ratio: 0.7

model:
  out_dim: 256
  base_model: "resnet18"
#  base_model: "resnet50"
#  pretrained: False    # default
  pretrained: True

dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 4
  valid_size: 0.20

loss:
  temperature: 0.5
  use_cosine_similarity: True
